### ISSUE TITLE
e549dd1 can't compile

### ISSUE THREAD

**Issue by lo585983** [bubble2k16/snes9x_3ds#68]
https://github.com/bubble2k16/snes9x_3ds/commit/e549dd1f1beff69a8cea819926ff112cbcb0b156

new src can't compile with 

    devkitARM r45
    libctru v1.0.0
    citro3d v1.0.0

any ideas ?

**Comment by asdolo** [comment]
Post your log in order to see what's happening there.

**Comment by lo585983** [comment]
c:/snes9x_3ds/source/3dssettings.h: In member function 'void ButtonMapping<Count
>::SetDoubleMapping(uint32, uint32)':
c:/snes9x_3ds/source/3dssettings.h:30:12: error: expected '(' before 'constexpr'

         if constexpr (Count > 0) {
            ^~~~~~~~~
c:/snes9x_3ds/source/3dssettings.h:33:12: error: expected '(' before 'constexpr'

         if constexpr (Count > 1) {
            ^~~~~~~~~
c:/snes9x_3ds/source/3dssettings.h:36:12: error: expected '(' before 'constexpr'

         if constexpr (Count > 2) {
            ^~~~~~~~~
c:/snes9x_3ds/source/3dssettings.h:41:5: error: expected '}' at end of input
     }
     ^
make[1]: *** [3dsmain.o] Error 1
make: *** [build] Error 2

**Comment by lo585983** [comment]
devkitARM r46
    libctru v1.4.0
    citro3d v1.3.0
not working too

**Comment by AdmiralCurtiss** [comment]
`if constexpr` needs C++17. Either remove the `constexpr` or update your compiler.

**Comment by lo585983** [comment]
devkitARM r47 <-- pass
but what version libctru & citro3d you use ? can you tell me ?

**Comment by AdmiralCurtiss** [comment]
1.3 for both, but yeah someone should probably update it so it works on libctru 1.4.

**Comment by roydmerkel** [comment]
I submitted a bug with a patch that allows it to compile with lubctru 1.4, but I don’t know if it’s the correct way to fix the issue, so I didn’t do a pull.
